export const ResponseCode = {
    SUCCESS: 200,
    SUCCESS_OK: 200,
    SUCCESS_CREATED: 201,
    SUCCESS_ACCEPTED: 202,
    SUCCESS_NO_CONTENT: 204,

    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    CONFLICT: 409,
    REQUEST_TIMEOUT: 408,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,

    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    DOES_NOT_EXIST: 510,
};

export const ResponseMessages = {
    SUCCESS: 'SUCCESS',
    SUCCESS_OK: 'SUCCESS_OK',
    SUCCESS_CREATED: 'Success!',
    SUCCESS_ACCEPTED: 'SUCCESS_ACCEPTED',
    SUCCESS_NO_CONTENT: 'SUCCESS_NO_CONTEN',
    SUCCESS_USER_DELETED: 'Record successfully deleted',

    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CREDENTIALS: 'These credentials do not match our records.',

    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWE',
    NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
    REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    TOO_MANY_REQUESTS: ' TOO_MANY_REQUESTS',

    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    BAD_GATEWAY: 'BAD_GATEWAY',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',

    TASK_CREATE_SUCCESS: 'Task created successfully',
    TASK_DELETE_SUCCESS: 'Task deleted successfully',
    TASK_UPDATE_SUCCESS: 'Task updated successfully',
    TASK_DEPENDENCIES_ADD_SUCCESS: 'Task dependecy created successfull',

    // Custom
    FAILED: 'FAILED',
    UPDATED: 'Update successful',
    NO_RECORD_FOUND: 'No records found',
    // to do 
    // add localization
    
};